# Generated by Django 2.2 on 2020-07-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc', models.TextField(max_length=11)),
                ('branch', models.TextField(max_length=200)),
                ('address', models.TextField(max_length=1000)),
                ('city', models.TextField(max_length=100)),
                ('district', models.TextField(max_length=50)),
                ('state', models.TextField(max_length=50)),
                ('bank', models.TextField(max_length=100)),
            ],
        ),
    ]
