# Generated by Django 2.2 on 2020-07-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banks',
            table='Banks',
        ),
    ]
